In [32]:
from sqlalchemy import create_engine
import pandas as pd 
import matplotlib.pyplot as plt

cnxn_string = ("postgresql+psycopg2://(username):{pswd}""@{host}:{port}/{database}")
print(cnxn_string)

postgresql+psycopg2://(username):{pswd}@{host}:{port}/{database}

In [33]:
engine = create_engine(cnxn_string.format(
    username="Local PostgreSQL",
    pswd="$kyline34R",
    host="localhost",
    port=5432,
    database="sqlda"
))

In [34]:
data = pd.read_csv (
    r"C:\Users\derek\OneDrive\Documents\44661_SQL Testing\country.csv",
    encoding='latin1',
    dtype={'zip_code': str}
)
data.head()

,code,name,continent,region,surfacearea,indepyear,population,lifeexpectancy,gnp,gnpold,localname,governmentform,headofstate,capital,code2
0,ABW,Aruba ...,North America ...,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix ...,129.0,AW
1,AFG,Afghanistan ...,Asia ...,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar ...,1.0,AF
2,AGO,Angola ...,Africa ...,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos ...,56.0,AO
3,AIA,Anguilla ...,North America ...,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II ...,62.0,AI
4,ALB,Albania ...,Europe ...,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani ...,34.0,AL

In [35]:
# Filter to only official languages
official_langs = data[data['IsOfficial'] == 'T']

# Count official languages per country
lang_counts = official_langs.groupby('CountryCode')['Language'].count().sort_values(ascending=False)

KeyError: 'IsOfficial'

In [ ]:
# Plot
plt.figure(figsize=(10, 6))
lang_counts.plot(kind='bar', color='skyblue')
plt.title('Number of Official Languages per Country')
plt.xlabel('Country Code')
plt.ylabel('Number of Official Languages')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()